### ISSUE TITLE
DB handling

### ISSUE THREAD

**Issue by frimtec** [frimtec/secure-sms-proxy#1]
DB handling in content provider:
- create in onCreate()
- move definition in manifest to bottom

**Comment by frimtec** [comment]
Android version: 29
Device: Google Pixel 2
App version: 1483
Thread name: main

Exception stack trace:
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.github.frimtec.android.pikettassist/com.github.frimtec.android.pikettassist.activity.MainActivity}: java.lang.IllegalStateException: attempt to re-open an already-closed object: SQLiteDatabase: /data/user/0/com.github.frimtec.android.securesmsproxy/databases/S2MSP.db
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3270)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409)
at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
at android.os.Handler.dispatchMessage(Handler.java:107)
at android.os.Looper.loop(Looper.java:214)
at android.app.ActivityThread.main(ActivityThread.java:7356)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
Caused by: java.lang.IllegalStateException: attempt to re-open an already-closed object: SQLiteDatabase: /data/user/0/com.github.frimtec.android.securesmsproxy/databases/S2MSP.db
at android.os.Parcel.createException(Parcel.java:2079)
at android.os.Parcel.readException(Parcel.java:2039)
at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:188)
at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:140)
at android.content.ContentProviderProxy.query(ContentProviderNative.java:423)
at android.content.ContentResolver.query(ContentResolver.java:944)
at android.content.ContentResolver.query(ContentResolver.java:880)
at android.content.ContentResolver.query(ContentResolver.java:836)
at com.github.frimtec.android.securesmsproxyapi.SecureSmsProxyFacadeImpl.isAllowed(SecureSmsProxyFacadeImpl.java:127)
at com.github.frimtec.android.pikettassist.activity.StateFragment.regularStates(StateFragment.java:183)
at com.github.frimtec.android.pikettassist.activity.StateFragment.createAdapter(StateFragment.java:173)
at com.github.frimtec.android.pikettassist.activity.AbstractListFragment.refresh(AbstractListFragment.java:51)
at com.github.frimtec.android.pikettassist.activity.AbstractListFragment.onCreateView(AbstractListFragment.java:42)
at android.app.Fragment.performCreateView(Fragment.java:2534)
at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1303)
at android.app.FragmentManagerImpl.addAddedFragments(FragmentManager.java:2431)
at android.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2210)
at android.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2166)
at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2067)
at android.app.FragmentManagerImpl.dispatchMoveToState(FragmentManager.java:3057)
at android.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:3004)
at android.app.FragmentController.dispatchActivityCreated(FragmentController.java:184)
at android.app.Activity.performCreate(Activity.java:7809)
at android.app.Activity.performCreate(Activity.java:7791)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1306)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3245)
... 11 more

--
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.
