### ISSUE TITLE
Crash-Report: NPE in deleteApplicationRule

### ISSUE THREAD

**Issue by frimtec** [frimtec/secure-sms-proxy#146]
```
App name: S2MSP (com.github.frimtec.android.securesmsproxy)
App version: 793087
Android version: 28
Device: samsung SM-G965U
Thread name: main

Exception stack trace:
java.lang.NullPointerException: Attempt to invoke virtual method 'com.github.frimtec.android.securesmsproxy.domain.Application com.github.frimtec.android.securesmsproxy.domain.ApplicationRule.getApplication()' on a null object reference
	at com.github.frimtec.android.securesmsproxy.ui.MainActivity.deleteApplicationRule(MainActivity.java:90)
	at com.github.frimtec.android.securesmsproxy.ui.MainActivity.lambda$onContextItemSelected$1$com-github-frimtec-android-securesmsproxy-ui-MainActivity(MainActivity.java:79)
	at com.github.frimtec.android.securesmsproxy.ui.MainActivity$$ExternalSyntheticLambda0.onClick(Unknown Source:4)
	at com.android.internal.app.AlertController$ButtonHandler.handleMessage(AlertController.java:184)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:6981)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1445)
```

**Comment by frimtec** [comment]
Resolved with release 2.2.2.
